# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Instala el controlador ODBC y herramientas relacionadas
RUN apt-get update && apt-get install -y bash gnupg2 curl \
&& curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
&& curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
&& apt-get update \
&& ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 unixodbc-dev \
&& rm -rf /var/lib/apt/lists/*

# Añade las herramientas SQL Server al PATH
ENV PATH="$PATH:/opt/mssql-tools18/bin:/usr/local/bin"

# instal postgresl client
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

# install Qdrant client
RUN apt-get update && apt-get install -y libgomp1 \
&& pip install qdrant-client

# install git
RUN apt-get update && apt-get install -y git

COPY ./*.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# NOT NEEDED IN DEV CONTAINERS --> REVIEW THE devcontainer.json FILE
COPY ./python_modules/* /app/python_modules/
COPY ./images /app/images/
COPY ./docs/* /app/docs/
COPY ./*.json /app/
COPY ./*.mp4 /app/
COPY ./*.py /app/
COPY ./.streamlit /app/.streamlit/

COPY ./data/scripts_summary /app/data/scripts_summary

# RUN cat /app/requirements.txt

EXPOSE 8501
EXPOSE 80

#### these commands cannot be executed here if you do not have the drive mounted.
#### these commands in Dev Containers must be executed as postCreateCommands.
# ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
